config/routes.rb
Rails.application.routes.draw do
  get '/', to: "application#home", as: :home
  get '/search_results', to: 'application#results', as: 'results'
  get '/destination_search', to: "application#search", as: 'search'
  get '/user_search', to: 'users#search', as: 'user_search'
  get '/login', to: 'users#login', as: 'login'
  post '/login', to: 'users#verify', as: 'verify'
  delete '/logout', to: 'users#logout', as: 'logout'
  post '/user_destinations/:id', to: 'user_destinations#create', as: 'user_destinations_create'
  post '/user_destinations/:id/add', to: 'user_destinations#add', as: 'user_destination_add'
  delete '/user_destinations/:id/remove', to: 'user_destinations#remove', as: 'user_destination_remove'
  resources :destination_locales
  resources :locales
  resources :destination_interests
  resources :user_interests
  resources :interests
  resources :user_destinations
  resources :destinations
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_interests
    has_many :interests, through: :user_interests
    has_many :user_destinations
    has_many :destinations, through: :user_destinations
    has_secure_password

    validates_presence_of :name, :username
    validates :password, presence: true, on: :create
    validates_uniqueness_of :username, :case_sensitive => false
    before_save { self.username.downcase! }

    def interested_destinations
      interestdestinations = []
      self.interests.ids.each do |i|
        interests = Destination.joins(:interests).where("interests.id = ?", i)
        interestdestinations << interests
      end
      interestdestinations.flatten.uniq
    end

    def interests=(interests_array)
      self.interests.clear
      interests_array.drop(1).each do |i|
        interest = Interest.find(i)
        self.interests << interest
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if session[:user]
      redirect_to user_path(User.find_by(username: session[:user]))
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user.username
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    #show pages require authentication for user to access
    #therefore session[:user] will always be present when accessing a user show
    logged_user = User.find_by(username: session[:user])
    #check to prevent errors when a user tries to access a user id show page that
    #does not exist
    if !User.find_by(id: params[:id])
      redirect_to user_path(logged_user)
    else
      @user = User.find(params[:id])
      loggeduser = User.find_by(username: session[:user])
      #check to make sure logged in users can only see their own show page
      if loggeduser != @user
        redirect_to user_path(logged_user)
      else
        @destinations = @user.interested_destinations - @user.destinations
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    session[:user] = @user.username
    redirect_to user_path(@user)
  end

  def login
    session.delete(:invalid)
  end

  def logout
    session.delete(:user)
    redirect_to home_path
  end

  def verify
    #check to see if any values are entered before hitting DB
    if login_fields
      @error = login_fields[1]
      @index = login_fields[0]
        if @index == 1
          @temp = params[:password]
        elsif @index == 2
          @temp = params[:username]
        end
      render :login
    #once all values are entered run verify process
    else
      @user = User.find_by(username: params[:username].downcase)
        if @user
          @user = @user.authenticate(params[:password])
            if @user
              session[:user] = @user.username
              redirect_to user_path(@user)
            else
              @error = "Invalid password entered."
              render :login
            end
        else
          @error = "Username does not exist."
          render :login
        end
    end
  end

  def login_fields
    if params[:username].empty? && params[:password].empty?
        return [0,"Please enter a username and password."]
    elsif params[:username].empty?
        return [1,"Please enter a username."]
    elsif params[:password].empty?
        return [2,"Please enter a password"]
    else
        return false
    end
  end

  private

    def user_params
      params.require(:user).permit(
        :name, :username, :password, interests:[])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |m| %>
  <li style="color: red">  <p><%= m %>
  <% end %>
  </p></li></ul>
  <% end %>



<%= form_for @user do |f| %>
<p><strong><%= f.label :name %></p></strong>
<%= f.text_field :name %><br><br>
<p><strong><%= f.label :username %></p></strong>
<%= f.text_field :username %><br>
<% if !@user.id %>
<p><strong><%= f.label :password %></p></strong>
<%= f.password_field :password %><br>
<% end %>
<p><strong><br><%= f.label :interests %></p></strong>
<p><%= f.collection_check_boxes(:interests, Interest.all.sort_by(&:name) ,:id, :name) do |z| %>
<%= z.label { z.check_box(checked: @user.interest_ids.include?(z.object.id)) + " " + z.text } %><br>
<% end %><br>
<%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>

    <br><br>
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:101.5%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center; padding-top: 0px;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>
  </div>
  <div class="eight wide column">


    <br><br>
    <h8>Edit your account.</h8>
    

    <%= render 'user_form' %>
  </div>
</div>

app/views/users/login.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <% random = random_destination %>
    <img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;">
    <p style="text-align: center;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>
  </div>
  <div class="eight wide column">
    <br><br>
    <h8>Please login.</h8>

    <% if session[:invalid] %>
      <p style="color: red"><br>Apologies. In order to access the exclusive features dérive offers, please log in.</p>
    <% end %>

    <% if @user %>
      <% if @user.errors.any? %>
        <ul>
        <% @user.errors.full_messages.each do |m| %>
        <p style="color: red"><li><%= m %></li></p>
        <% end %> </ul>
      <% end %>
    <% end %>

    <% if @error %>
      <br><br><p style="color: red"><%= @error %></p>
    <% end %>


    <%= form_tag "/login", method: "post" %><br>
      <p><strong><%= label_tag :username %><br></strong>
      <% if @index == 2 %>
        <%= text_field_tag :username, @temp %><br>
      <% else %>
        <%= text_field_tag :username %><br>
        <% end %>
      <p><strong><%= label_tag :password %></strong><br>
      <% if @index == 1 %>
        <%= password_field_tag :password, @temp %><br><br></p>
      <% else %>
        <%= password_field_tag :password %><br><br></p>
      <% end %>
      <%= submit_tag "Login" %><br><br>


      <h7>No dérive account?</h7>
      <p>No problem. Click <a href="/users/new">here</a> to make your dérive account.</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>

    <br><br>
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:101.5%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center; padding-top: 0px;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>
  </div>
  <div class="eight wide column">


    <br><br>
    <h8>Create your account.</h8>
    <p>Ready to find your next travel destination? Create an account today to unlock all that dérive has to offer. Please fill out the form below to complete your user profile. From there, dérive can provide the most compatible destinations.</p>

    <%= render 'user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>

    <br><br>
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:101.5%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center; padding-top: 0px;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>
  </div>

  <div class="eight wide column">
    <br><br>
    <h8>Hi there,<br> <%= @user.name %>.</h8><br><br>

    <div class="ui cards">
      <div class="card">
        <div class="content">
          <div class="header"><h6>Username</h6></div>
          <div class="meta">
            <ul>
              <li style="color: black"><p><%= @user.username %></p></li>
            </ul>
          </div>
          <div class="description">
            <h6 style="color: black;">Your Interests:</h6>
            <% if @user.interests.empty? %>
            <ul>
            <li><p style="color:#BF5241;">Looks like you haven't selected any interests yet. Add some!</p></li>
            </ul>
            <%= form_tag edit_user_path(@user), method: 'get' do %>
            <%= submit_tag "Edit User Profile" %>
            <% end %>
            <% else %>
              <ul>
                <% @user.interests.each do |i| %>
                <li style="color: black"><p><%= i.name %></p></li>
                <% end %>
              </ul>
          </div>
          <%= form_tag edit_user_path(@user), method: 'get' do %>
          <%= submit_tag "Edit User Profile" %>
          <% end %>
        </div>
      </div>
    </div>
    <br><br>
    <h6>Your dérive Destinations:</h6>
    <p>&nbsp;&nbsp;Add your favorite destinations to your dérive Destinations.</p>
    <% if @user.destinations.empty? %>
    <p style="color:#BF5241;">&nbsp;&nbsp;&nbsp;Select some destinations!</p>
    <% else %>
      <ul>
        <% @user.destinations.sort_by(&:city).each do |d| %>
        <li><p><%= link_to "#{d.city}, #{d.country}", destination_path(d) %> <button><%= link_to "Remove", user_destination_remove_path(UserDestination.find_by(user: @user.id, destination: d.id)), method: "DELETE" %></button></p></li>
        <% end %>
      </ul>
    <% end %><br>
    <% if @destinations.empty? %>
      <h6>All recommended destinations have been added.</h6>
      <p>Add some more interests for additional recommendations!</p>
    <% else %>
      <h6>Destination Recommendations:</h6>
      <p>&nbsp;&nbsp;Based on your user profile, we recommend the following destinations.</p>
      <ul>
        <% @destinations.sort_by(&:city).each do |d| %>
          <li><p><%= link_to "#{d.city}, #{d.country}", destination_path(d)%> <button><%= link_to "Add", user_destination_add_path(d), method: "POST" %></button></p></li>
          <% end %> </ul>
    <% end %>
    <% end %>
</div>





<!-- OLD STUFF BELOW -->