config/routes.rb
Rails.application.routes.draw do
  get '/', to: "application#home", as: :home
  get '/search_results', to: 'application#results', as: 'results'
  get '/destination_search', to: "application#search", as: 'search'
  get '/user_search', to: 'users#search', as: 'user_search'
  get '/login', to: 'users#login', as: 'login'
  post '/login', to: 'users#verify', as: 'verify'
  delete '/logout', to: 'users#logout', as: 'logout'
  post '/user_destinations/:id', to: 'user_destinations#create', as: 'user_destinations_create'
  post '/user_destinations/:id/add', to: 'user_destinations#add', as: 'user_destination_add'
  delete '/user_destinations/:id/remove', to: 'user_destinations#remove', as: 'user_destination_remove'
  resources :destination_locales
  resources :locales
  resources :destination_interests
  resources :user_interests
  resources :interests
  resources :user_destinations
  resources :destinations
  resources :users
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :destination_interests
  has_many :interests, through: :destination_interests
  has_many :user_destinations
  has_many :users, through: :user_destinations
  has_many :destination_locales
  has_many :locales, through: :destination_locales

  def self.search(searchparams)
    if searchparams[:interests].nil? && searchparams[:locales].nil? && searchparams[:english?].empty? && searchparams[:budget].empty?
      return Destination.all.sort_by(&:city)
    end

    destinations = []
    if !searchparams[:interests].nil?
      searchparams[:interests].each do |i|
        interests = Destination.joins(:interests).where("interests.id = ?",i)
        destinations << interests
      end
    end

    if !searchparams[:locales].nil?
      searchparams[:locales].each do |l|
        locales = Destination.joins(:locales).where("locales.id = ?",l)
        destinations << locales
      end
    end

    if !searchparams[:budget].empty?
      destinations << Destination.where(budget: searchparams[:budget])
    end


    if !searchparams[:english?].empty?
      destinations << Destination.where(english: searchparams[:english?])
    end

    destinationhash = {}
    destinations.flatten.each do |d|
      if destinationhash[d]
        destinationhash[d] += 1
      else
        destinationhash[d] = 1
      end
    end
    return destinationhash.sort_by {|k, v| v}.reverse
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def show
    @destination = Destination.find(params[:id])
    @user = User.find_by(username: session[:user])
  end

  def index
    @destinations = Destination.all.sort_by(&:city)
  end


end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/index.html.erb
<div class="ui grid">
  <div class="ten wide column" style="padding-right: 0px;">
    <div class="gallery">
    <% @destinations.each do |destination| %>
        <%= link_to destination_path(destination) do %>
            <%= image_tag destination.image, class: "gallery-image"%>
            <p style="text-align: center"><strong><%= destination.city %>, <%= destination.country %></strong></p>
        <% end %>
    <% end %>
    </div>

  </div>
  <div class="six wide column">
    <br><br>
    <h8>dérive Destinations.</h8>
    <p>Learn more about all of the travel destinations dérive offers.<br>
      Click each image to read about each destination.</p>
  </div>
</div>

app/views/destinations/show.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <img src="<%= @destination.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;">
    <div class="">
    &nbsp;&nbsp;<h7><%= @destination.city %>, <%= @destination.country %></h7>

    <% if @user.destinations.include?(@destination) %>
      <button id="user-button"><%= link_to "Remove from your dérive Destinations", user_destination_path(UserDestination.find_by(user: @user.id, destination: @destination.id)), method: "DELETE", data: {confirm: "Please confirm that you would like to remove #{@destination.city}, #{@destination.country} from your dérive Destinations."}%></button>
    <% else %>
      <button id="user-button"><%= link_to "Add to your dérive Destinations", user_destinations_create_path(@destination), method: "POST", data: {confirm: "Please confirm that you would like to add #{@destination.city}, #{@destination.country} to your dérive Destinations."}%></button>
    <% end %>


  </div>
</div>

  <div class="eight wide column">
    <br><br>
    <h8>Learn more about <br><%= @destination.city %>.</h8>


    <br><br>
    <div class="wrapper">
    <div class="ui icon message" id="test">
      &nbsp;<i class="comment outline icon"></i>
      <div class="content">
        <div class="header">
          <h6>Is English primarily spoken in <%= @destination.city %>?</h6>
        </div>
          <% if @destination.english == true %>
            <p>Yes, English is the primary language spoken in <%= @destination.country %>.</p>
          <% else @destination.english == false %>
            <p>No, English is not the primary language spoken in <%= @destination.country %>.</p>
          <% end %>
      </div>
    </div>
    </div>
    <br>
    <div class="wrapper">
    <div class="ui icon message" id="test">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="dollar sign icon"></i>
      <div class="content">
        <div class="header">
          <h6>&nbsp;&nbsp;How expensive is <%= @destination.city %>?</h6>
        </div>
          <% if @destination.budget == "$" %>
          <p>&nbsp;&nbsp;&nbsp;You should expect to spend $20-$50 a day in <%= @destination.city%>.</p>
          <% elsif @destination.budget == "$$" %>
          <p>&nbsp;&nbsp;&nbsp;You should expect to spend $50-$100 a day in <%= @destination.city%>.</p>
          <% elsif @destination.budget == "$$$" %>
          <p>&nbsp;&nbsp;&nbsp;You should expect to spend $100-$200 a day in <%= @destination.city%>.</p>
          <% elsif @destination.budget == "$$$$" %>
          <p>&nbsp;&nbsp;&nbsp;You should expect to spend $200+ a day in <%= @destination.city%>.</p>
          <% end %>
      </div>
    </div>
    </div>
    <br>
    <div class="wrapper">
    <div class="ui icon message" id="test">
      &nbsp;&nbsp;<i class="suitcase icon"></i>
      <div class="content">
        <div class="header">
          <h6>What is the ideal travel group for <%= @destination.city %>?</h6>
        </div>
          <p>dérive's size recommendation for <%= @destination.city %> is <strong><%= @destination.group.downcase %></strong>.</p>
      </div>
    </div>
    </div>
    <br>
    <div class="wrapper">
    <div class="ui icon message" id="test">
      &nbsp;&nbsp;&nbsp;&nbsp;<i class="tree icon"></i>
      <div class="content2">
        <div class="header">
          <h6>What type of locales does <%= @destination.city %> offer?</h6>
        </div>
        <% dest_locales = @destination.locales.sort_by(&:name).map do |dest| %>
          <% dest.name %>
        <% end %>
        <h10><%= dest_locales.join(", ") %></h10>

      </div>
    </div>
    </div>
    <br>
    <div class="wrapper">
    <div class="ui icon message" id="test">
      &nbsp;&nbsp;<i class="flag icon"></i>
      <div class="content2">
        <div class="header">
          <h6>What interests can you pursue in <%= @destination.city %>?</h6>
        </div>
        <% dest_interests = @destination.interests.sort_by(&:name).map do |dest| %>
          <% dest.name %>
        <% end %>
        <h10><%= dest_interests.join(", ") %></h10>

      </div>
    </div>
    </div>
    <br>



  </div>
</div>