config/routes.rb
Rails.application.routes.draw do
  get '/', to: "application#home", as: :home
  get '/search_results', to: 'application#results', as: 'results'
  get '/destination_search', to: "application#search", as: 'search'
  get '/user_search', to: 'users#search', as: 'user_search'
  get '/login', to: 'users#login', as: 'login'
  post '/login', to: 'users#verify', as: 'verify'
  delete '/logout', to: 'users#logout', as: 'logout'
  post '/user_destinations/:id', to: 'user_destinations#create', as: 'user_destinations_create'
  post '/user_destinations/:id/add', to: 'user_destinations#add', as: 'user_destination_add'
  delete '/user_destinations/:id/remove', to: 'user_destinations#remove', as: 'user_destination_remove'
  resources :destination_locales
  resources :locales
  resources :destination_interests
  resources :user_interests
  resources :interests
  resources :user_destinations
  resources :destinations
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :destination_interests
  has_many :interests, through: :destination_interests
  has_many :user_destinations
  has_many :users, through: :user_destinations
  has_many :destination_locales
  has_many :locales, through: :destination_locales

  def self.search(searchparams)
    if searchparams[:interests].nil? && searchparams[:locales].nil? && searchparams[:english?].empty? && searchparams[:budget].empty?
      return Destination.all.sort_by(&:city)
    end

    destinations = []
    if !searchparams[:interests].nil?
      searchparams[:interests].each do |i|
        interests = Destination.joins(:interests).where("interests.id = ?",i)
        destinations << interests
      end
    end

    if !searchparams[:locales].nil?
      searchparams[:locales].each do |l|
        locales = Destination.joins(:locales).where("locales.id = ?",l)
        destinations << locales
      end
    end

    if !searchparams[:budget].empty?
      destinations << Destination.where(budget: searchparams[:budget])
    end


    if !searchparams[:english?].empty?
      destinations << Destination.where(english: searchparams[:english?])
    end

    destinationhash = {}
    destinations.flatten.each do |d|
      if destinationhash[d]
        destinationhash[d] += 1
      else
        destinationhash[d] = 1
      end
    end
    return destinationhash.sort_by {|k, v| v}.reverse
  end

end

app/models/destination_interest.rb
class DestinationInterest < ApplicationRecord
  belongs_to :destination
  belongs_to :interest
end

app/models/destination_locale.rb
class DestinationLocale < ApplicationRecord
  belongs_to :destination
  belongs_to :locale
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests
  has_many :destination_interests
  has_many :destinations, through: :destination_interests
end

app/models/locale.rb
class Locale < ApplicationRecord
  has_many :destination_locales
  has_many :destinations, through: :destination_locales
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_interests
    has_many :interests, through: :user_interests
    has_many :user_destinations
    has_many :destinations, through: :user_destinations
    has_secure_password

    validates_presence_of :name, :username
    validates :password, presence: true, on: :create
    validates_uniqueness_of :username, :case_sensitive => false
    before_save { self.username.downcase! }

    def interested_destinations
      interestdestinations = []
      self.interests.ids.each do |i|
        interests = Destination.joins(:interests).where("interests.id = ?", i)
        interestdestinations << interests
      end
      interestdestinations.flatten.uniq
    end

    def interests=(interests_array)
      self.interests.clear
      interests_array.drop(1).each do |i|
        interest = Interest.find(i)
        self.interests << interest
      end
    end

end

app/models/user_destination.rb
class UserDestination < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :random_destination
  before_action :authorized, except: [:home, :login, :new, :verify, :create]

  def home
    @random = random_destination
  end

  def random_destination
    @random = Destination.all.sample
  end

  def search
    @destinations = Destination.all.sort_by(&:city)
    @search = [] #to allow for check if filters exists
  end

  def results
    @destinations = Destination.search(params[:search])
    #check for the scenario where search params are empty
    if @destinations == Destination.all.sort_by(&:city)
      @search = []
    else
      @search = params[:search]
    end
    render :search
  end

  def authorized
    if !session[:user]
      session[:invalid] = true
      render "/users/login"
    end
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def show
    @destination = Destination.find(params[:id])
    @user = User.find_by(username: session[:user])
  end

  def index
    @destinations = Destination.all.sort_by(&:city)
  end


end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if session[:user]
      redirect_to user_path(User.find_by(username: session[:user]))
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user.username
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    #show pages require authentication for user to access
    #therefore session[:user] will always be present when accessing a user show
    logged_user = User.find_by(username: session[:user])
    #check to prevent errors when a user tries to access a user id show page that
    #does not exist
    if !User.find_by(id: params[:id])
      redirect_to user_path(logged_user)
    else
      @user = User.find(params[:id])
      loggeduser = User.find_by(username: session[:user])
      #check to make sure logged in users can only see their own show page
      if loggeduser != @user
        redirect_to user_path(logged_user)
      else
        @destinations = @user.interested_destinations - @user.destinations
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    session[:user] = @user.username
    redirect_to user_path(@user)
  end

  def login
    session.delete(:invalid)
  end

  def logout
    session.delete(:user)
    redirect_to home_path
  end

  def verify
    #check to see if any values are entered before hitting DB
    if login_fields
      @error = login_fields[1]
      @index = login_fields[0]
        if @index == 1
          @temp = params[:password]
        elsif @index == 2
          @temp = params[:username]
        end
      render :login
    #once all values are entered run verify process
    else
      @user = User.find_by(username: params[:username].downcase)
        if @user
          @user = @user.authenticate(params[:password])
            if @user
              session[:user] = @user.username
              redirect_to user_path(@user)
            else
              @error = "Invalid password entered."
              render :login
            end
        else
          @error = "Username does not exist."
          render :login
        end
    end
  end

  def login_fields
    if params[:username].empty? && params[:password].empty?
        return [0,"Please enter a username and password."]
    elsif params[:username].empty?
        return [1,"Please enter a username."]
    elsif params[:password].empty?
        return [2,"Please enter a password"]
    else
        return false
    end
  end

  private

    def user_params
      params.require(:user).permit(
        :name, :username, :password, interests:[])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destination_locales_helper.rb
module DestinationLocalesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/user_destinations_helper.rb
module UserDestinationsHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">

    <img src="<%= @random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;">
    <p style="text-align: center;"><%= @random.city %>, <%= @random.country %>  •  <a href="/destinations/<%= @random.id %>">Learn More</a>
  </div>
  <div class="eight wide column">
    <br><br>
    <h8>Welcome to dérive.</h8>
    <p>At dérive, we strive to provide you with a travel destination, specifically tailored to your needs. Once you build your user profile, dérive will craft a curated list of desirable destinations for your next trip.

    <br><br>

    <strong>Would you rather perform a custom search instead?</strong><br>
    You can find our DestinationFinder™ <%= link_to "here", "/destination_search"%>. Additionally, you can browse all of our dérive-approved destinations <%= link_to "here", destinations_path%>.

    <br><br>

    <strong>Have questions?</strong><br>
    Reach out to our dérive Concierge who are waiting to answer your questions. <a href="mailto:p6doyle@outlook.com?subject=Dérive Inquiry" target="_blank">Email</a> us today.</p>

  </div>
</div>

app/views/application/search.html.erb
<div class="ui grid">
  <div class="eight wide column" style="padding-right: 0px;">
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:100%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>

    <br><br>
    <% random = random_destination %>
    <a href="/destinations/<%= random.id %>"><img src="<%= random.image %>" style="object-fit: cover; object-position: 100% 0; width:101.5%; height: 430px; padding-right: 5px;"></a>
    <p style="text-align: center; padding-top: 0px;"><%= random.city %>, <%= random.country %>  •  <a href="/destinations/<%= random.id %>">Learn More</a>
  </div>
  <div class="eight wide column">
    <br><br>
    <h8>DestinationFinder™</h8>
    <p>
    <% if @user %>
      <i><%= @user.name %>, search for your next curated destination using the interactive search form below.</i>
    <% else %>
      Search for your next curated destination using the interactive search form below.<br><br>
      Not all fields are required for dérive to recommend destinations.<br>
      When selecting your <i>interests</i> and <i>locales</i>, please press ⌘ and click to select more than one option .</p>
    <% end %>

    <div class="row4">
      <%= form_tag "/search_results", method: "get" %>
      <div class="column4" style="background-color:#D2BD9D;">
        <h7>Interests</h7><br>
        <p>What do you like to do?</p><br>
        <%= select_tag "search[interests]", options_for_select(Interest.all.sort_by(&:name).collect{ |i| [i.name, i.id] }), multiple: true, size: 7 %><br>
    </div>
      <div class="column4" style="background-color:#85746B;">
        <h7>Locales</h7>
        <p>What type of environment excites you?</p><br>
        <%= select_tag "search[locales]", options_for_select(Locale.all.sort_by(&:name).collect{ |l| [l.name, l.id] }), multiple: true, size: 5 %> <br>
      </div>
      <div class="column4" style="background-color:#AC8870;">
        <h7>Budget & Language</h7>
        <p>What is your budget?</p>
        <%= select_tag "search[budget]", options_for_select(["$", "$$", "$$$", "$$$$"]), include_blank: 'Select a budget'%><br><br>
        <p>Do you prefer English speaking destinations?</p>
        <%= select_tag "search[english?]", options_for_select([['Yes', 1], ['No', 0]]), include_blank: 'Select preference'%><br><br>
        <b><%= submit_tag 'Search for Destinations'%></b> <br>
      </div>
    </div><br><br>
    <% if !@search.empty? %>
        <h7>dérive Destinations filtered <br>by your preferences:</h7>
        <p>The destinations at the top of the list are the most compatible with your travel preferences.</p>
        <ul>
        <% @destinations.each do |d, value| %>
        <li><p><%= link_to "#{d.city}, #{d.country} (#{value} matches)", destination_path(d)%></p></li>
        <% end %> </ul>

      <% else %>

        <br>
        <h7>All <i>Dérive</i> Destinations:</h7>
        <ul>
        <% @destinations.each do |d| %>
        <li><p><%= link_to "#{d.city}, #{d.country}", destination_path(d)%></p></li>
        <% end %> </ul>
    <% end %>
  </div>
</div>